Don't skip RTCE/RTCF fail - fix instead
It seems the error:

TypeError: unsupported type for persistent hash keying: <class 'complex'>

at

kernel = op2.Kernel(ast, ast.name, requires_zeroed_output_arguments=True)

when running

w_v = interpolate(v, W)

is real since on dual_base_fiat branches one can happily interpolate
into RTCE/RTCF so I likely need to find the underlying cause somewhere
in my changes.